In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf


In [ ]:
tf.__version__

'2.15.0'

In [ ]:
df=pd.read_csv("/content/Churn_Modelling.csv")

In [ ]:
x=df.iloc[:,3:-1].values
y=df.iloc[:,-1].values

In [ ]:
df.describe()

RowNumber    CustomerId   CreditScore           Age        Tenure  \
count  10000.00000  1.000000e+04  10000.000000  10000.000000  10000.000000   
mean    5000.50000  1.569094e+07    650.528800     38.921800      5.012800   
std     2886.89568  7.193619e+04     96.653299     10.487806      2.892174   
min        1.00000  1.556570e+07    350.000000     18.000000      0.000000   
25%     2500.75000  1.562853e+07    584.000000     32.000000      3.000000   
50%     5000.50000  1.569074e+07    652.000000     37.000000      5.000000   
75%     7500.25000  1.575323e+07    718.000000     44.000000      7.000000   
max    10000.00000  1.581569e+07    850.000000     92.000000     10.000000   

             Balance  NumOfProducts    HasCrCard  IsActiveMember  \
count   10000.000000   10000.000000  10000.00000    10000.000000   
mean    76485.889288       1.530200      0.70550        0.515100   
std     62397.405202       0.581654      0.45584        0.499797   
min         0.000000       1.000000      0.00000        0.000000   
25%         0.000000       1.000000      0.00000        0.000000   
50%     97198.540000       1.000000      1.00000        1.000000   
75%    127644.240000       2.000000      1.00000        1.000000   
max    250898.090000       4.000000      1.00000        1.000000   

       EstimatedSalary        Exited  
count     10000.000000  10000.000000  
mean     100090.239881      0.203700  
std       57510.492818      0.402769  
min          11.580000      0.000000  
25%       51002.110000      0.000000  
50%      100193.915000      0.000000  
75%      149388.247500      0.000000  
max      199992.480000      1.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [ ]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [ ]:
print (y)

[1 0 1 ... 1 1 0]


In [ ]:
df.isna().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [ ]:
#encoding the categorical data


In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x[:,2]=le.fit_transform(x[:,2])

In [ ]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [ ]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct= ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])], remainder='passthrough')
x= np.array(ct.fit_transform(x))

In [ ]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [ ]:
#feature scaling  **To be done after train test split

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
#fit_transform is done only on the training dataset and not on the test dataset
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)



In [ ]:
#building an ANN model
ann = tf.keras.models.Sequential()   #keras is a library and models is a module
                                     # and Sequential is a class


In [ ]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))  #add is a keyword
# keras is a library and layers is module and Dense is a class
# relu is the activation function


In [ ]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [ ]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

In [ ]:
#compilling the ANN
ann.compile(optimizer= 'adam',loss='binary_crossentropy',metrics=['accuracy'])

In [ ]:
#training the ann
ann.fit(x_train,y_train,batch_size= 32,epochs=100)

Epoch 1/100
250/250 [==============================] - 3s 3ms/step - loss: 0.6800 - accuracy: 0.6283
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 0.5398 - accuracy: 0.7959
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4865 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4605 - accuracy: 0.7956
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4423 - accuracy: 0.8024
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4320 - accuracy: 0.8090
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4257 - accuracy: 0.8138
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4213 - accuracy: 0.8189
Epoch 9/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4181 - accuracy: 0.8207
Epoch 10/100
250/250 [==============================] - 1s 5ms/step - loss: 0.4153 - accura

In [ ]:
#prdiction of the values

y_pred =ann.predict(x_test)

63/63 [==============================] - 0s 2ms/step


In [ ]:
#predicting a particular row ** 0.5 is the threshold value
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]])) >0.5)

1/1 [==============================] - 0s 39ms/step
[[False]]


In [ ]:
print (y_pred > 0.5)

[[False]
 [False]
 [False]
 ...
 [False]
 [False]
 [False]]


In [ ]:
print (y_test)

[0 1 0 ... 0 0 0]


In [ ]:
y_pred=y_pred >0.5
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm= confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1538   57]
 [ 222  183]]


0.8605